[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]

thirtyfour = "0.36.1"
tokio = { version = "1", features = ["full"] }
teloxide="0.13.0"
regex="1"
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.41"
